apiVersion: v1
kind: Service
metadata:
	name: example-nginx-service
	labels:
		app: example-nginx
spec:
	selector:
		app: example-nginx
	ports:
		- protocol: TCP
			port: 80
			targetPort: 80
	type: ClusterIP

	# To expose externally for testing you could use:
	# type: NodePort
	# ports:
	#   - port: 80
	#     targetPort: 80
	#     nodePort: 30080

